### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by tas50**

### CODE REVIEW

**Comment by tas50** [comment]
Hey there. It's great to see you're interested in a chef project. We're glad to have you as a contributor. Since this is your first time ocntributing I'm here to offer you a bit of extra help.

**Comment by tas50** [comment]
Hey there. It's great to see you're interested in a chef project. We're glad to have you as a contributor. Since this is your first time ocntributing I'm here to offer you a bit of extra help.

**Comment by thommay** [comment]
what if I don't want to `ocntributing`

**Comment by tas50** [comment]
Perhaps someone can craft the real wording to use...

**Pull request closed without merging**
